Pat solutions
pulsarcomet/readability pull request #2
Opened 2021-04-29 09:19 UTC by rpatycr

Adding my refactor to the class for points 1 - 5.

2021-04-29 09:28 UTC, pulsarcomet requested changes

2021-04-29 09:28 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
>  This function returns reversed signed integer of size 32 bits if possible, otherwise 0
Let's put this description before the method reverse_integer

2021-04-29 09:28 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
> +      with self.assertRaises(Exception):
use ValueError (see below)

2021-04-29 09:28 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
> +            raise Exception('Incorrect parameters: generator and regular values cannot be input together')
ValueError would be more relevant here rather than general Exception

2021-04-29 09:28 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
> +    if (numbers):
brackets might be omitted

2021-04-29 09:28 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
> +def reverse_integers(*numbers, ignore_sign=True, max_int_size=31):
consider here / to enforce positional and keyword-only args

2021-04-29 09:39 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
> +            a= float(str(abs(x))[::-1])
PEP8 spaces around =

2021-04-29 09:39 UTC, pulsarcomet commented on chapter_3_functions/reverse_integer_PatCr.py
> +
no need in empty line

2021-05-04 11:38 UTC, rpatycr commented on chapter_3_functions/reverse_integer_PatCr.py
>  This function returns reversed signed integer of size 32 bits if possible, otherwise 0
done

2021-05-04 11:38 UTC, rpatycr commented on chapter_3_functions/reverse_integer_PatCr.py
> +      with self.assertRaises(Exception):
Thanks, I agree.

2021-05-04 11:40 UTC, rpatycr commented on chapter_3_functions/reverse_integer_PatCr.py
> +            a= float(str(abs(x))[::-1])
Opps!, fixed it.

2021-05-05 08:11 UTC, pulsarcomet approved these changes

2021-05-05 08:11 UTC, merged